name: pontaagro
description: A Ponta project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  path: ^1.8.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  match: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqflite_common_ffi: ^2.2.5
  mockito: ^5.4.2
  build_runner: ^2.4.5
  match_generator: ^0.4.2

flutter:
  uses-material-design: true

  #dart run build_runner build -d

  # assets:
  #   - assets/icon/ponta.png

  