name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  flutter_test:
    name: Run Flutter analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-java@v3.10.0
        with:
          distribution: 'zulu'
          java-version: '12.x'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: "stable"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: dart format -o none --set-exit-if-changed lib/
      - run: dart format -o none --set-exit-if-changed test/
      - run: flutter test --coverage
      - run: flutter test --machine > test-results.json
      - uses: VeryGoodOpenSource/very_good_coverage@v2.1.0
        with:
          min_coverage: 20
